/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyLiftRouteImport } from './routes/my-lift'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as MusclesIndexRouteImport } from './routes/muscles.index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as OnboardingResultsRouteImport } from './routes/onboarding.results'
import { Route as OnboardingPremiumRouteImport } from './routes/onboarding.premium'
import { Route as MusclesSlugRouteImport } from './routes/muscles.$slug'
import { Route as ExercisesSlugRouteImport } from './routes/exercises.$slug'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingPremiumRouteImport } from './routes/onboarding.premium'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLiftRoute = MyLiftRouteImport.update({
  id: '/my-lift',
  path: '/my-lift',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const MusclesIndexRoute = MusclesIndexRouteImport.update({
  id: '/muscles/',
  path: '/muscles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingResultsRoute = OnboardingResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPremiumRoute = OnboardingPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => OnboardingRoute,
} as any)
const MusclesSlugRoute = MusclesSlugRouteImport.update({
  id: '/muscles/$slug',
  path: '/muscles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesSlugRoute = ExercisesSlugRouteImport.update({
  id: '/exercises/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPremiumRoute = OnboardingPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/my-lift': typeof MyLiftRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/tracker': typeof TrackerRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/onboarding/premium': typeof OnboardingPremiumRoute
  '/onboarding/results': typeof OnboardingResultsRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/muscles/': typeof MusclesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/my-lift': typeof MyLiftRoute
  '/pricing': typeof PricingRoute
  '/tracker': typeof TrackerRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/onboarding/premium': typeof OnboardingPremiumRoute
  '/onboarding/results': typeof OnboardingResultsRoute
  '/exercises': typeof ExercisesIndexRoute
  '/muscles': typeof MusclesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/my-lift': typeof MyLiftRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/tracker': typeof TrackerRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/muscles/$slug': typeof MusclesSlugRoute
  '/onboarding/premium': typeof OnboardingPremiumRoute
  '/onboarding/results': typeof OnboardingResultsRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/muscles/': typeof MusclesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/my-lift'
    | '/onboarding'
    | '/pricing'
    | '/tracker'
    | '/exercises/$slug'
    | '/muscles/$slug'
    | '/onboarding/premium'
    | '/onboarding/results'
    | '/exercises/'
    | '/muscles/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/my-lift'
    | '/pricing'
    | '/tracker'
    | '/exercises/$slug'
    | '/muscles/$slug'
    | '/onboarding/premium'
    | '/onboarding/results'
    | '/exercises'
    | '/muscles'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/my-lift'
    | '/onboarding'
    | '/pricing'
    | '/tracker'
    | '/exercises/$slug'
    | '/muscles/$slug'
    | '/onboarding/premium'
    | '/onboarding/results'
    | '/exercises/'
    | '/muscles/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  MyLiftRoute: typeof MyLiftRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
  TrackerRoute: typeof TrackerRoute
  ExercisesSlugRoute: typeof ExercisesSlugRoute
  MusclesSlugRoute: typeof MusclesSlugRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  MusclesIndexRoute: typeof MusclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lift': {
      id: '/my-lift'
      path: '/my-lift'
      fullPath: '/my-lift'
      preLoaderRoute: typeof MyLiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/muscles/': {
      id: '/muscles/'
      path: '/muscles'
      fullPath: '/muscles/'
      preLoaderRoute: typeof MusclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/results': {
      id: '/onboarding/results'
      path: '/results'
      fullPath: '/onboarding/results'
      preLoaderRoute: typeof OnboardingResultsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/premium': {
      id: '/onboarding/premium'
      path: '/premium'
      fullPath: '/onboarding/premium'
      preLoaderRoute: typeof OnboardingPremiumRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/muscles/$slug': {
      id: '/muscles/$slug'
      path: '/muscles/$slug'
      fullPath: '/muscles/$slug'
      preLoaderRoute: typeof MusclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$slug': {
      id: '/exercises/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof ExercisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingPremiumRoute: typeof OnboardingPremiumRoute
  OnboardingResultsRoute: typeof OnboardingResultsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingPremiumRoute: OnboardingPremiumRoute,
  OnboardingResultsRoute: OnboardingResultsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  MyLiftRoute: MyLiftRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
  TrackerRoute: TrackerRoute,
  ExercisesSlugRoute: ExercisesSlugRoute,
  MusclesSlugRoute: MusclesSlugRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  MusclesIndexRoute: MusclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
